mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00000.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00001.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00002.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00003.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00004.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00005.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00006.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00007.bson
mongorestore -h dev-mongodb-01.awsservers.mobiquitynetworks.com -d backend -c statistics restore/development/part-m-00008.bson
