mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00000.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00001.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00002.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00003.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00004.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00005.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00006.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00007.bson
mongorestore -h prod-mongodb-01-a.awsservers.mobiquitynetworks.com -d backend -c statistics restore/production/part-m-00008.bson
